/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul7_1.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author Ridha Nadhira F
 */
public class frame7_11 extends javax.swing.JFrame {

    /**
     * Creates new form frame7_11
     */
    public frame7_11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        balok = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pjgblk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbrblk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tgiblk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hitungbalok = new javax.swing.JButton();
        kubus = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pjgkubus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hitungkubus = new javax.swing.JButton();
        bola = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jaribola = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hitungbola = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        balok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        balok.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("cm");
        balok.add(jLabel1);
        jLabel1.setBounds(290, 30, 40, 30);

        pjgblk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pjgblk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjgblkActionPerformed(evt);
            }
        });
        balok.add(pjgblk);
        pjgblk.setBounds(170, 30, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Masukkan Panjang : ");
        balok.add(jLabel3);
        jLabel3.setBounds(20, 30, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Masukkan Lebar : ");
        balok.add(jLabel4);
        jLabel4.setBounds(20, 70, 140, 30);

        lbrblk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbrblk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbrblkActionPerformed(evt);
            }
        });
        balok.add(lbrblk);
        lbrblk.setBounds(170, 70, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("cm");
        balok.add(jLabel5);
        jLabel5.setBounds(290, 70, 40, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Masukkan Tinggi : ");
        balok.add(jLabel6);
        jLabel6.setBounds(20, 110, 140, 30);

        tgiblk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tgiblk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgiblkActionPerformed(evt);
            }
        });
        balok.add(tgiblk);
        tgiblk.setBounds(170, 110, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("cm");
        balok.add(jLabel7);
        jLabel7.setBounds(290, 110, 40, 30);

        hitungbalok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hitungbalok.setText("Hitung");
        hitungbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungbalokActionPerformed(evt);
            }
        });
        balok.add(hitungbalok);
        hitungbalok.setBounds(270, 150, 110, 30);

        jTabbedPane1.addTab("Balok", balok);

        kubus.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi : ");
        kubus.add(jLabel8);
        jLabel8.setBounds(20, 30, 160, 30);

        pjgkubus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pjgkubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjgkubusActionPerformed(evt);
            }
        });
        kubus.add(pjgkubus);
        pjgkubus.setBounds(40, 70, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("cm");
        kubus.add(jLabel9);
        jLabel9.setBounds(160, 70, 40, 30);

        hitungkubus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hitungkubus.setText("Hitung");
        hitungkubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungkubusActionPerformed(evt);
            }
        });
        kubus.add(hitungkubus);
        hitungkubus.setBounds(220, 70, 110, 30);

        jTabbedPane1.addTab("Kubus", kubus);

        bola.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-jari : ");
        bola.add(jLabel10);
        jLabel10.setBounds(20, 30, 190, 30);

        jaribola.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jaribola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaribolaActionPerformed(evt);
            }
        });
        bola.add(jaribola);
        jaribola.setBounds(40, 70, 110, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("cm");
        bola.add(jLabel11);
        jLabel11.setBounds(160, 70, 40, 30);

        hitungbola.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hitungbola.setText("Hitung");
        hitungbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungbolaActionPerformed(evt);
            }
        });
        bola.add(hitungbola);
        hitungbola.setBounds(220, 70, 110, 30);

        jTabbedPane1.addTab("Bola", bola);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 400, 280);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Perhitungan Volume Bangun Ruang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 330, 30);

        setBounds(0, 0, 416, 379);
    }// </editor-fold>//GEN-END:initComponents

    private void pjgblkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjgblkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjgblkActionPerformed

    private void lbrblkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbrblkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbrblkActionPerformed

    private void tgiblkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgiblkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgiblkActionPerformed

    private void hitungbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungbalokActionPerformed
        // TODO add your handling code here:
        int panjang,lebar,tinggi;
        panjang=Integer.parseInt(pjgblk.getText());
        lebar=Integer.parseInt(lbrblk.getText());
        tinggi=Integer.parseInt(tgiblk.getText());
        int hasil = panjang*lebar*tinggi;

        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"HASIL HITUNG",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hitungbalokActionPerformed

    private void pjgkubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjgkubusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjgkubusActionPerformed

    private void hitungkubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungkubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi=Integer.parseInt(pjgkubus.getText());
        int hasil = sisi*sisi*sisi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Kubus Adalah :"+hasil,"HASIL HITUNG",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hitungkubusActionPerformed

    private void jaribolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaribolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaribolaActionPerformed

    private void hitungbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungbolaActionPerformed
        // TODO add your handling code here:
        int jari;
        jari = Integer.parseInt(jaribola.getText());
        int hasil=4*(22/7)*jari*jari;
        try{
            JOptionPane.showMessageDialog(null,"Volume Bola Adalah :"+hasil,"HASIL HITUNG",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hitungbolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame7_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame7_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame7_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame7_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame7_11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel balok;
    private javax.swing.JPanel bola;
    private javax.swing.JButton hitungbalok;
    private javax.swing.JButton hitungbola;
    private javax.swing.JButton hitungkubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jaribola;
    private javax.swing.JPanel kubus;
    private javax.swing.JTextField lbrblk;
    private javax.swing.JTextField pjgblk;
    private javax.swing.JTextField pjgkubus;
    private javax.swing.JTextField tgiblk;
    // End of variables declaration//GEN-END:variables
}
